title: jsondb                 <script async type="text/javascript">var REPO="jsondb";var DESC="PHP: Read / write JSON and mixed data to SQL database";</script><script async type="text/javascript" src="/topmenu.js"></script>
description: PHP: Read / write JSON and mixed data to SQL database
